server:
  port: 8585


spring:

  # database migration
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration"
    validate-on-migrate: false
    out-of-order: true

  # enhance development
  devtools:
    reload:
      trigger-file: .reloadtrigger
    restart:
      exclude: "static/**,public/**"


  # database config
  datasource:
    #containername:3306
    url: jdbc:sqlserver://ticketeasy.database.windows.net:1433;database=ticket_easy;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #username and password in the container
    username: elonsol
    password: ticketEasy999$



  # jpa config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServer2012Dialect

  data:
    rest:
      base-path: /api

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    user:
      name: mostafa

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  server:
    port: 

application-description: 'World Cup Ticket Reservation'
application-version: 1.0.0




#okta:
#  oauth2:
#    client-id: 0oa7rwsfxudacn6wp5d7
#    issuer: https://dev-52007706.okta.com/oauth2/default
#    client-secret: RN76V8KB17OUPUJIVhhp3WAKzv3SCx1IyB_RCTHw


security:
  secret_key: world_cup
  bearer: Bearer

